#!/usr/bin/env node
/**
 * Netlify Build Script - Inject Environment Variables
 * 
 * This script runs during Netlify build to inject environment variables
 * into a JavaScript file that can be loaded in the browser.
 * 
 * Environment Variables (set in Netlify dashboard as secrets):
 * - RAILWAY_API_URL: The Railway API server URL
 * - RAILWAY_API_KEY: The Railway API authentication key
 */

const fs = require('fs');
const path = require('path');

// Get environment variables from Netlify
const RAILWAY_API_URL = process.env.RAILWAY_API_URL || '';
const RAILWAY_API_KEY = process.env.RAILWAY_API_KEY || '';

// Generate the config JavaScript file
const configContent = `/**
 * Railway API Configuration
 * Generated automatically during Netlify build from environment variables
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on each build
 */

// Inject environment variables into window object
(function() {
  if (typeof window !== 'undefined') {
    // Railway API URL from Netlify environment
    window.RAILWAY_API_URL = '${RAILWAY_API_URL}';
    
    // Railway API Key from Netlify environment (secret)
    window.RAILWAY_API_KEY = '${RAILWAY_API_KEY}';
    
    // Debug info (only shows if values are set)
    if (window.RAILWAY_API_URL) {
      console.log('[Railway Config] API URL configured from environment');
    }
    
    if (window.RAILWAY_API_KEY) {
      console.log('[Railway Config] API Key configured from environment');
    }
  }
})();
`;

// Output path
const outputPath = path.join(__dirname, '..', 'www', 'assets', 'js', 'railway-env.js');

// Write the config file
try {
  fs.writeFileSync(outputPath, configContent, 'utf8');
  console.log('✅ Railway environment configuration generated successfully');
  console.log(`   Output: ${outputPath}`);
  
  if (RAILWAY_API_URL) {
    console.log(`   API URL: ${RAILWAY_API_URL}`);
  } else {
    console.warn('⚠️  RAILWAY_API_URL not set in environment variables');
  }
  
  if (RAILWAY_API_KEY) {
    console.log('   API Key: [CONFIGURED]');
  } else {
    console.warn('⚠️  RAILWAY_API_KEY not set in environment variables');
  }
  
  console.log('\n💡 Note: Users can still override these values in the UI');
} catch (error) {
  console.error('❌ Error generating Railway environment configuration:', error);
  process.exit(1);
}
